
services:
  db:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    env_file:
      - .env
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  web:
#   image: edmonddusa/kotlin-engineer-challenge-web:latest
   ports:
     - "8080:3000"
   restart: always
   env_file:
     - .env
   environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_PORT=${POSTGRES_PORT}
     - POSTGRES_HOST=db
   build:
     context: .
     dockerfile: Dockerfile
   depends_on:
     - db